# Generated by Django 5.2.6 on 2025-10-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_alter_category_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="phone_number",
        ),
        migrations.AlterField(
            model_name="profile",
            name="facebook",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="profile",
            name="instagram",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="profile",
            name="tik_tok",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="profile",
            name="twitter",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="profile",
            name="website",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="profile",
            name="whatsapp",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
