# Generated by Django 5.2.6 on 2025-10-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="barcode",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.UniqueConstraint(
                fields=("user", "barcode"), name="unique_barcode_per_user"
            ),
        ),
    ]
