# Generated by Django 5.2.6 on 2025-10-12 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_alter_inventoryitem_barcode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
